### ISSUE TITLE
Dependency on ch.qos.logback:logback-classic:1.0.9

### ISSUE THREAD

**Issue by brianpcarr** [jfrog/artifactory-client-java#43]
Please remove the compile dependency on ch.qos.logback:logback-classic jar file.

A work around is for the user to create a logback.xml file to block debug level messages before moving to production, but slf4j has better solutions.

**Comment by rbrindl** [comment]
I know the last message on this issue was more than two years ago, but since it is still open:
In the latest released version (2.2.0) of artifactory-java-client-services there is still a compile dependency on logback.
This, among other hard dependencies, prevents me from using this otherwise quite useful library.

**Comment by eyalbe4** [comment]
Hi @rbrindl,
Do you think you'll be able to create a pull request with the required changes? That way you'll also be test the changes locally and make sure it works properly with your code.
